project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN

base_path: "."
preserve_hierarchy: true

files:
  - source: /translation/source/*.xml
    translation: /translation/dest/%locale%_%original_file_name%
