name: Crowdin source push

on:
  push:
    paths:
        - 'translation/source/mobile.xml'
    branches: [ main ]

jobs:
  crowdin-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Crowdin push
        uses: crowdin/github-action@v2
        with:
          upload_sources: true
          upload_translations: false
          download_translations: false
          # only push mobile source
          # we don't want to push lila sources!
          upload_translations_args: "--preserve-hierarchy -b '[lichess-org.mobile] main' -s '/translation/source/mobile.xml' -t '/translation/dest/%file_name%/%locale%.%file_extension%"
        env:
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
